on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.3
      # Run steps with continue-on-error and capture output
      - name: Run dart format
        id: dart_format
        continue-on-error: true
        run: dart format --set-exit-if-changed .

      - name: Run flutter pub get
        id: flutter_pub_get
        continue-on-error: true
        run: flutter pub get

      - name: Run flutter analyze
        id: flutter_analyze
        continue-on-error: true
        run: flutter analyze

      - name: Run flutter test
        id: flutter_test
        continue-on-error: true
        run: flutter test

      - name: Run flutter build apk
        id: flutter_build_apk
        continue-on-error: true
        run: flutter build apk --debug --split-per-abi

      # Check for failures using step outcomes
      - name: Check for failures
        id: check_failures
        run: |
          echo "Checking for failures..."
          FAILED_STEPS=""
          if [[ "${{ steps.dart_format.outcome }}" != "success" ]]; then
            FAILED_STEPS+="dart format\n"
          fi
          if [[ "${{ steps.flutter_pub_get.outcome }}" != "success" ]]; then
            FAILED_STEPS+="flutter pub get\n"
          fi
          if [[ "${{ steps.flutter_analyze.outcome }}" != "success" ]]; then
            FAILED_STEPS+="flutter analyze\n"
          fi
          if [[ "${{ steps.flutter_test.outcome }}" != "success" ]]; then
            FAILED_STEPS+="flutter test\n"
          fi
          if [[ "${{ steps.flutter_build_apk.outcome }}" != "success" ]]; then
            FAILED_STEPS+="flutter build apk\n"
          fi

          if [[ -n "$FAILED_STEPS" ]]; then
            echo "The following steps failed:"
            echo -e "$FAILED_STEPS"
            echo "has_failures=true" >> $GITHUB_ENV
          else
            echo "All steps succeeded."
            echo "has_failures=false" >> $GITHUB_ENV
          fi

      # Fail the workflow if any step failed
      - name: Fail workflow if any step failed
        if: ${{ env.has_failures == 'true' }}
        run: |
          echo "One or more steps failed. Failing the workflow."
          exit 1

      # Push APK to Releases (only if no failures)
      - name: Push APK to Releases
        if: ${{ env.has_failures == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: "build/app/outputs/apk/debug/*.apk"
