on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.3
      # Run steps with continue-on-error and capture output
      - name: Run dart format
        id: dart_format
        continue-on-error: true
        run: |
          echo "Running dart format..."
          if ! dart format --set-exit-if-changed .; then
            echo "dart_format_status=failed" >> $GITHUB_ENV
            echo "::error::dart format failed"
          fi

      - name: Run flutter pub get
        id: flutter_pub_get
        continue-on-error: true
        run: |
          echo "Running flutter pub get..."
          if ! flutter pub get; then
            echo "flutter_pub_get_status=failed" >> $GITHUB_ENV
            echo "::error::flutter pub get failed"
          fi

      - name: Run flutter analyze
        id: flutter_analyze
        continue-on-error: true
        run: |
          echo "Running flutter analyze..."
          if ! flutter analyze; then
            echo "flutter_analyze_status=failed" >> $GITHUB_ENV
            echo "::error::flutter analyze failed"
          fi

      - name: Run flutter test
        id: flutter_test
        continue-on-error: true
        run: |
          echo "Running flutter test..."
          if ! flutter test; then
            echo "flutter_test_status=failed" >> $GITHUB_ENV
            echo "::error::flutter test failed"
          fi

      - name: Run flutter build apk
        id: flutter_build_apk
        continue-on-error: true
        run: |
          echo "Running flutter build apk..."
          if ! flutter build apk --debug --split-per-abi; then
            echo "flutter_build_apk_status=failed" >> $GITHUB_ENV
            echo "::error::flutter build apk failed"
          fi

      # Check for failures and print summary
      - name: Check for failures
        id: check_failures
        run: |
          echo "Checking for failures..."
          FAILED_STEPS=""
          if [[ "${{ env.dart_format_status }}" == "failed" ]]; then
            FAILED_STEPS+="dart format\n"
          fi
          if [[ "${{ env.flutter_pub_get_status }}" == "failed" ]]; then
            FAILED_STEPS+="flutter pub get\n"
          fi
          if [[ "${{ env.flutter_analyze_status }}" == "failed" ]]; then
            FAILED_STEPS+="flutter analyze\n"
          fi
          if [[ "${{ env.flutter_test_status }}" == "failed" ]]; then
            FAILED_STEPS+="flutter test\n"
          fi
          if [[ "${{ env.flutter_build_apk_status }}" == "failed" ]]; then
            FAILED_STEPS+="flutter build apk\n"
          fi

          if [[ -n "$FAILED_STEPS" ]]; then
            echo "The following steps failed:"
            echo -e "$FAILED_STEPS"
            echo "has_failures=true" >> $GITHUB_ENV
          else
            echo "All steps succeeded."
            echo "has_failures=false" >> $GITHUB_ENV
          fi

      # Fail the workflow if any step failed
      - name: Fail workflow if any step failed
        if: ${{ env.has_failures == 'true' }}
        run: |
          echo "One or more steps failed. Failing the workflow."
          exit 1

      # Push APK to Releases (only if no failures)
      - name: Push APK to Releases
        if: ${{ env.has_failures == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
